AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - test/**/*.rb
    - vendor/**/*
    - scripts/**/*
    - simple-immutable.gemspec

Naming/FileName:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Lint/IneffectiveAccessModifier:
  Enabled: false