AllCops:
  Exclude:
    - bin/**/*
    - test/**/*
    - scripts/**/*
    - ./*.gemspec
    - Gemfile
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/MissingCopEnableDirective:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Lint/IneffectiveAccessModifier:
  Enabled: false
